### ISSUE TITLE
Game restarts when you go down the New Bark Town stairs 

### ISSUE THREAD

**Issue by BasileiatonRhomaion** [Sierraffinity/CrystalDust#14] opened 2020-12-26 04:53 UTC
I don't know why but I got the game simply got the .bps file from the github and used an unzipped Emerald file to apply the patch  and did what you would usually when starting a Pokémon game only for me to then try to walk down the stairs and the game just restarts the particular emulator I used was MyBoy and the patcher I used was JS ROM Patcher

And here's what I mean and I only made it this long to show that I wasn't doing anything to cause the issue 
https://m.youtube.com/watch?v=Aa8_ZgIJZYw&feature=youtu.be

**Comment by Sierraffinity** [comment] 2020-12-26 04:59
Able to replicate, has something to do with the screen fade itself, somehow, despite screen fades working elsewhere... Adding the BIOS and disabling speed hacks do not work, they actually cause the _emulator_ to crash instead of just the game.

**Comment by BasileiatonRhomaion** [comment] 2020-12-26 05:06
Well the emulator doesn't crash it just restarts the game though I'm sure this issue could be limited to the emulator or not I'll find out by getting a different emulator

**Comment by BasileiatonRhomaion** [comment] 2020-12-26 05:12
Well got a different emulator and I could go down the stairs no problem meaning the emulator is the issue I understand why you hate emulator reports Becuase people use different emulators and each of them have their own issues.

**Comment by Sierraffinity** [comment] 2020-12-26 05:13
No I just mean I hate investigating them since they're inconvenient haha, I'm still going to look into it since My Boy! is a commonly used emulator.

**Comment by Sierraffinity** [comment] 2020-12-26 05:23
It's specifically to do with the implementation of staircases, somehow, because all other warps that use the same codepath for fading the screen work fine. Fascinating but I think I'll have to leave this for another day, I'm pooped.

**Comment by Sierraffinity** [comment] 2020-12-27 02:32
This was caused by a null dereference creating an undefined opcode with the modern compiler, which My Boy! does _not_ appreciate. Fixed by #330cd898.

**Closed** 2020-12-28 00:39 UTC
