### ISSUE TITLE
Pokédex Area Checker Issue

### ISSUE THREAD

**Issue by WispySkiesVT** [Sierraffinity/CrystalDust#37] opened 2022-01-14 01:44 UTC
The Area checker in the Pokédex shows the Hoenn map but locates the player as if it was in Johto and is not equal with what I suspect is the Johto location highlights for a Pokémon.

**Comment by Sierraffinity** [comment] 2022-01-23 01:01
Duplicate of #29.

**Closed by Sierraffinity** 2022-01-23 01:01 UTC
